// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkMQEVac28QtwOkr78T7WJLn0tzO73uPw',
    appId: '1:973317291741:web:75e375fb2866e19e512534',
    messagingSenderId: '973317291741',
    projectId: 'ai-finance-coach',
    authDomain: 'ai-finance-coach.firebaseapp.com',
    storageBucket: 'ai-finance-coach.firebasestorage.app',
    measurementId: 'G-RQMDM4NCXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm9gJScKBU-zYZugQc-XX9Cm4ZURqYHFU',
    appId: '1:973317291741:android:eae47902437276ff512534',
    messagingSenderId: '973317291741',
    projectId: 'ai-finance-coach',
    storageBucket: 'ai-finance-coach.firebasestorage.app'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMxtyu2fyHPYmhXsMLQRFiUv5969P0E7Y',
    appId: '1:973317291741:ios:86f0f7dea7effb5e512534',
    messagingSenderId: '973317291741',
    projectId: 'ai-finance-coach',
    storageBucket: 'ai-finance-coach.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMxtyu2fyHPYmhXsMLQRFiUv5969P0E7Y',
    appId: '1:973317291741:ios:86f0f7dea7effb5e512534',
    messagingSenderId: '973317291741',
    projectId: 'ai-finance-coach',
    storageBucket: 'ai-finance-coach.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkMQEVac28QtwOkr78T7WJLn0tzO73uPw',
    appId: '1:973317291741:web:3139d90793e5fe0f512534',
    messagingSenderId: '973317291741',
    projectId: 'ai-finance-coach',
    authDomain: 'ai-finance-coach.firebaseapp.com',
    storageBucket: 'ai-finance-coach.firebasestorage.app',
    measurementId: 'G-KLPY8F2PC4',
  );

}